# Generated by Django 4.0.1 on 2022-01-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attacker_table',
            fields=[
                ('attack_event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attack_asn', models.TextField(max_length=100)),
                ('attack_city', models.TextField(max_length=100)),
                ('attack_country_code', models.TextField(max_length=100)),
                ('attack_isp', models.TextField(max_length=100)),
                ('attack_lat', models.TextField(max_length=100)),
                ('attack_log', models.TextField(max_length=100)),
                ('attack_region_name', models.TextField(max_length=100)),
                ('attack_zip', models.TextField()),
                ('org', models.TextField(max_length=100)),
                ('target_os', models.TextField(max_length=100)),
                ('target_country', models.TextField(max_length=100)),
                ('target_id', models.TextField()),
                ('target_ip', models.TextField()),
                ('target_region', models.TextField(max_length=100)),
                ('target_status', models.TextField(max_length=100)),
                ('target_type', models.TextField(max_length=100)),
                ('attack_threat_severity', models.TextField(max_length=100)),
                ('event_detection_type', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'attacker_table',
            },
        ),
    ]
