# Generated by Django 4.0 on 2022-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='data222',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_threat_class', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
