import { PRIVATE_TYPES } from '@babel/types'
import mock from '../mock'
import { paginateArray } from '../utils'

const data = [
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    status: 1,
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Trojan',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: 2,
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech ',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'DOS',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:08',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: 3,
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech ',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:10',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: 1,
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech ',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'SQL Injection',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: 5,
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech ',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Phising',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: 3,
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: 1,
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4',
    org_id:'WhizHack Tech',
    asset_name:'Router',
    asset_type:'End-point',
    asset_id:'1231',
    source_ip:'123.123.122',
    source_location:'Taiwan',
    source_country:'China',
    status2:1
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  },
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "Korrie O'Crevy",
    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    attack_threat_type: 'Stealer',
    city: 'Krasnosilka',
    time_stamp: '2021-11-09 14:50:07',
    salary: '$23896.35',
    age: '61',
    experience: '1 Year',
    status: '2',
    target_endpoint: 'Null',
    target_ip: '160.44.201.156',
    target_os:'Null',
    interface:'Null',
    asn:'Null',
    attacker_mac_address: '12:34:56:78:9a:bc',  
    attacker_host_ip:'172.18.0.4'
  }
]

mock.onGet('/api/datatables/initial-data').reply(config => {
  return [200, data]
})

mock.onGet('/api/datatables/data').reply(config => {
  // eslint-disable-next-line object-curly-newline
  const { q = '', perPage = 10, page = 1 } = config
  /* eslint-enable */

  const queryLowered = q.toLowerCase()
  const filteredData = data.filter(
    item =>
      /* eslint-disable operator-linebreak, implicit-arrow-linebreak */
      item.full_name.toLowerCase().includes(queryLowered) ||
      item.post.toLowerCase().includes(queryLowered) ||
      item.email.toLowerCase().includes(queryLowered) ||
      item.age.toLowerCase().includes(queryLowered) ||
      item.salary.toLowerCase().includes(queryLowered) ||
      item.time_stamp.toLowerCase().includes(queryLowered) ||
      item.attack_threat_type.toLowerCase().includes(queryLowered) ||
      item.target_endpoint.toLowerCase().includes(queryLowered) ||
      item.target_ip.toLowerCase().includes(queryLowered) ||
      item.target_os.toLowerCase().includes(queryLowered) ||
      item.interface.toLowerCase().includes(queryLowered) ||
      item.asn.toLowerCase().includes(queryLowered) ||
      item.attacker_mac_address.toLowerCase().includes(queryLowered) ||
      item.attacker_host_ip.toLowerCase().includes(queryLowered) ||
      item.start_date.toLowerCase().includes(queryLowered)
  )
  /* eslint-enable  */

  return [
    200,
    {
      allData: data,
      invoices: paginateArray(filteredData, perPage, page),
      total: filteredData.length
    }
  ]
})
